{
 "title": "shinpuru",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "shinpuru-latest,shinpuru-canary"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Discord Events Trigger Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(discord_eventtriggers_total{job=\"$instance\"}[$interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "REST API Request Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(restapi_requests_total{job=\"$instance\"}[$interval])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "# goroutines / threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$instance\"}",
     "legendFormat": "# goroutines"
    },
    {
     "expr": "go_threads{job=\"$instance\"}",
     "legendFormat": "# threads"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$instance\"}/1024/1024",
     "legendFormat": "MiB alloc"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"$instance\"}/1024/1024",
     "legendFormat": "MiB sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$instance\"}/1024/1024",
     "legendFormat": "MiB heap idle"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$instance\"}/1024/1024",
     "legendFormat": "MiB heap inuse"
    }
   ]
  },
  {
   "title": "Discord Gateway Ping RTT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discord_gatewayping{job=\"$instance\"}",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Command Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(discord_commands_prcessed_total{job=\"$instance\"}[$interval])",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}