package static

const (
	DiDiscordSession            = "discordgosession"
	DiConfig                    = "config"
	DiDatabase                  = "database"
	DiObjectStorage             = "objectstorage"
	DiLifecycleTimer            = "lifecycletimer"
	DiPermissions               = "permissions"
	DiGhostpingIgnoreMiddleware = "ghostpingignoremiddleware"
	DiTwitchNotifyWorker        = "twitchnotifyworker"
	DiTwitchNotifyListener      = "twitchnotifylistener"
	DiOneTimeAuth               = "onetimeauthhandler"
	DiConfigParser              = "configparser"
	DiLegacyCommandHandler      = "skcommandhandler"
	DiCommandHandler            = "kencommandhandler"
	DiMetrics                   = "metrics"
	DiWebserver                 = "webserver"
	DiBackupHandler             = "backuphandler"
	DiDiscordOAuthModule        = "discordoauthmodule"
	DiOAuthHandler              = "oauthhandler"
	DiAuthAccessTokenHandler    = "authaccesstokenhandler"
	DiAuthRefreshTokenHandler   = "authrefreshtokenhandler"
	DiAuthAPITokenHandler       = "authapitokenhandler"
	DiAuthMiddleware            = "authmiddleware"
	DiCodeExecFactory           = "codeexecfactory"
	DiKarma                     = "karmaservice"
	DiReport                    = "reportservice"
	DiGuildLog                  = "guildlog"
	DiKVCache                   = "kvcache"
	DiRedis                     = "redisclient"
	DiState                     = "dgstate"
)
