package static

const (
	DiDiscordSession            = "discordgosession"
	DiConfig                    = "config"
	DiDatabase                  = "database"
	DiObjectStorage             = "objectstorage"
	DiLifecycleTimer            = "lifecycletimer"
	DiPermissionMiddleware      = "permissionmiddleware"
	DiGhostpingIgnoreMiddleware = "ghostpingignoremiddleware"
	DiTwitchNotifyWorker        = "twitchnotifyworker"
	DiTwitchNotifyListener      = "twitchnotifylistener"
	DiOneTimeAuth               = "onetimeauthhandler"
	DiConfigParser              = "configparser"
	DiCommandHandler            = "skcommandhandler"
	DiMetrics                   = "metrics"
	DiWebserver                 = "webserver"
	DiBackupHandler             = "backuphandler"
	DiDiscordOAuthModule        = "discordoauthmodule"
	DiOAuthHandler              = "oauthhandler"
	DiAuthAccessTokenHandler    = "authaccesstokenhandler"
	DiAuthRefreshTokenHandler   = "authrefreshtokenhandler"
	DiAuthAPITokenHandler       = "authapitokenhandler"
	DiAuthMiddleware            = "authmiddleware"
)
