name: Backend Linting

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  unit_tests:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.23'
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run Linting
        run: task lint-be
